const listOfCountry = [
  {"name": "Egypt", "code": "eg"},
  {"name": "Morocco", "code": "ma"},
  {"name": "United Arab Emirates", "code": "ae"},
  {"name": "UK", "code": "gb"},
  {"name": "Turkey", "code": "tr"},
  {"name": "USA", "code": "us"},
  {"name": "Russia", "code": "ru"},
  {"name": "France", "code": "fr"},
  {"name": "Germany", "code": "de"},
  {"name": "china", "code": "cn"},
  {"name": "Canada", "code": "ca"},
  {"name": "Italy", "code": "it"},
  {"name": "Japan", "code": "jp"},
  {"name": "Brazil", "code": "br"},
  {"name": "Belgium", "code": "be"},
  {"name": "Sweden", "code": "se"},
  {"name": "South Africa", "code": "za"},
  {"name": "MEXICO", "code": "mx"},
  {"name": "INDIA", "code": "in"},
  {"name": "New Zealand", "code": "nz"},
  {"name": "Indonesia", "code": "id"},
];

const listOfCatagory = [
  {"name": "science", "code": "science"},
  {"name": "business", "code": "business"},
  {"name": "technology", "code": "technology"},
  {"name": "sports", "code": "sports"},
  {"name": "health", "code": "health"},
  {"name": "general", "code": "general"},
  {"name": "entertainment", "code": "entertainment"},
  {"name": "ALL", "code": null},
];
const listOfNewsChannel = [
  {"name": "BBC News", "code": "bbc-news"},
  {"name": "The Times of India", "code": "the-times-of-india"},
  {"code": "politico", "name": "politico"},
  {"code": "the-washington-post", "name": "The Washington Post"},
  {"code": "reuters", "name": "reuters"},
  {"code": "cnn", "name": "cnn"},
  {"code": "nbc-news", "name": "nbc news"},
  {"code": "the-hill", "name": "The Hill"},
  {"code": "fox-news", "name": "Fox News"},
];
